### ISSUE TITLE
File Not Found in Colab

### ISSUE THREAD

**Issue by CJWBW** [facebookresearch/ic_gan#13]
Hi, I am trying to run the **Generate images with IC-GAN + CLIP!** section in Colab, but got error:

`FileNotFoundError: [Errno 2] No such file or directory: '/content/icgan_biggan_imagenet_res256_nofeataug/state_dict_best0.pth'`

Can only see directory `icgan_biggan_imagenet_res256`

**Comment by sjwhitmore** [comment]
I fixed this myself by replacing this line:

if gen_model == 'icgan':  
  **experiment_name = 'icgan_biggan_imagenet_res256_nofeataug'**
else:
  experiment_name = 'cc_icgan_biggan_imagenet_res256_nofeataug'

with this line:
if gen_model == 'icgan':  
  **experiment_name = 'icgan_biggan_imagenet_res256'**
else:
  experiment_name = 'cc_icgan_biggan_imagenet_res256_nofeataug'

assume the authors will update but should work for you in the meantime!

**Comment by CJWBW** [comment]
> I fixed this myself by replacing this line:
> 
> if gen_model == 'icgan':
> **experiment_name = 'icgan_biggan_imagenet_res256_nofeataug'**
> else:
> experiment_name = 'cc_icgan_biggan_imagenet_res256_nofeataug'
> 
> with this line:
> if gen_model == 'icgan':
> **experiment_name = 'icgan_biggan_imagenet_res256'**
> else:
> experiment_name = 'cc_icgan_biggan_imagenet_res256_nofeataug'
> 
> assume the authors will update but should work for you in the meantime!

Thank you! Thought to fix the same way but was just wondering whether the `_nofeataug` model is the same as the other ones

**Comment by ArantxaCasanova** [comment]
Yes, it is the same model. Fixed in the Colab notebook code.
