### ISSUE TITLE
JSON config files for reproducing the results in the paper? 

### ISSUE THREAD

**Issue by Qianli-ion** [facebookresearch/ic_gan#16]
Thanks for releasing the code! 

Quick question, is there anyway we can get the training configuration files in JSON for both the BigGAN and StyleGAN2 experiments as part of the `--json_config` input to the `run.py`?

**Comment by ArantxaCasanova** [comment]
Hello,

you can find the config files for BigGAN in [here](https://github.com/facebookresearch/ic_gan/tree/main/BigGAN_PyTorch/config_files) and for StyleGAN2 backbone in [here](https://github.com/facebookresearch/ic_gan/tree/main/stylegan2_ada_pytorch/config_files/COCO_Stuff).

**Comment by Qianli-ion** [comment]
Hi Arantxa, Thanks a lot for the config files!
