### ISSUE TITLE
Rationale on excluding conditional instance image from the kNN  

### ISSUE THREAD

**Issue by Qianli-ion** [facebookresearch/ic_gan#20]
The _obtain_nns function is coded in such a way that excluding the 0-NN (the conditioned instance itself) as shown here https://github.com/facebookresearch/ic_gan/blob/4428c9188ff9e6658b1062b8c19c13135298f561/data_utils/datasets_common.py#L742

Can I ask the rationale of excluding the image of the conditional instance from the k-NN? Doing this will also exclude the image during the training process for this specific condition right? Even if the image will be included in some other conditions, wouldn't this exclusion encourage the algorithm to learn a conditional distribution with a "hole" at the center? 

Any intuition and design thought would be much appreciated. Thanks!

**Comment by ArantxaCasanova** [comment]
Hello,
that's right! By not using the input conditioning sample in the neighborhood distribution, we encourage IC-GAN to generate samples that look like other neighbors instead of focusing on reconstructing the input instance. The desired behavior of IC-GAN is to generate variations of the input instance, rather than reconstructing it.

**Comment by Qianli-ion** [comment]
Hey Arantxa,
Thanks for the reply! Hmm...i guess that make sense. Having the network to generate new samples that's similar to the conditioned one but not exactly the same, as we already have the conditioned image. But if we view the algorithm as a realization of the Kernel Density Estimation perspective in the paper, this exclusion will make a "dip" at the center of the conditional PDF which is a bit strange to my eyes. Was including 0-NN ever been attempted during the development?

**Comment by ArantxaCasanova** [comment]
That is a good point. We haven't properly tested what happens if we include the 0-NN. We have thought about it, but we followed our design choice and didn't include it. It wouldn't be incorrect to include it, and it might be an interesting experiment to do.

**Comment by Qianli-ion** [comment]
I see I see. Thanks for the reply! I'll actually give this one a shot, since in my application the presence of the conditioned image is important.
